ignore:
  target:
    entity:
      integration: best_bottrop_garbage_collection
  fields:
    days:
      example: 2
      selector:
       number:
         min: 0
         max: 365
         step: 1
         mode: box